name: "Update project item status"
description: "Update project item status"
inputs:
  project_token:
    description: "Authentication token for GitHub GraphQL API (project scope)"
    required: true
  pr_action:
    description: "pull_request or pull_request_review github.event.action"
    required: true
  pr_state:
    description: "pull_request_review github.event.review.state (for pull_request action == '')"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
